### ISSUE TITLE
checkpoint-8972

### ISSUE THREAD

**Issue by Hsome-DB** [iriscxy/FES#2]

**Comment by lanxojin** [comment]
hello, i find the linked URL of checkpoint-8972 is invalid. Could you please tell me how you solved this problem?
Thanks.

**Comment by iriscxy** [comment]
Hi, I think the url is still valid. You can check it: https://drive.google.com/file/d/1_XQ49dh07i6KNw3tE8H_WxXU9H3I94us/view

**Comment by lanxojin** [comment]
thanks for your reply.
