### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by MoLICHENXI** [iriscxy/FES#3]
Thank you for your creative work! However, I have a question while running your code. In the following **_Seq2SeqLMOutput_** block, the parameters **zero_logits** and **q_e_concat** don't exist in the **_init_** function of the **Seq2SeqLMOutput class**. The code also throws an error when it reaches this part. I'd like to ask how I should modify this part of the code to make it run correctly, or perhaps my understanding is incorrect? Looking forward to your reply!

https://github.com/iriscxy/FES/blob/f68e551e234433f685f44ca070b92579dbe0c3f2/magic_bart.py#L351-L362

**Comment by iriscxy** [comment]
Hi, you can modify the corresponding interface in the transformer package code. Specifically, you need to look in the transformers/modeling_outputs.py file within the Seq2SeqLMOutput class, which is a subclass of ModelOutput.

**Comment by MoLICHENXI** [comment]
So what I understand is that in the transformers/modeling_outputs.py file of the Seq2SeqLMOutput function to add two parameters _zero_logits, q_e_concat_ initialization statement.And how do I initialize these two parameters in a specific format, a simple **torch.FloatTensor** form?

**Comment by iriscxy** [comment]
```
class Seq2SeqLMOutput(ModelOutput):
    loss: Optional[torch.FloatTensor] = None
    logits: torch.FloatTensor = None
    past_key_values: Optional[Tuple[Tuple[torch.FloatTensor]]] = None
    decoder_hidden_states: Optional[Tuple[torch.FloatTensor]] = None
    decoder_attentions: Optional[Tuple[torch.FloatTensor]] = None
    cross_attentions: Optional[Tuple[torch.FloatTensor]] = None
    encoder_last_hidden_state: Optional[torch.FloatTensor] = None
    encoder_hidden_states: Optional[Tuple[torch.FloatTensor]] = None
    encoder_attentions: Optional[Tuple[torch.FloatTensor]] = None
    zero_logits: Optional[Tuple[torch.FloatTensor]] = None
    q_e_concat: Optional[Tuple[torch.FloatTensor]] = None
```
